# -*- coding: utf-8 -*-
"""MoneyWiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m50M9FEDENXA6RCtm0t-r9PbSzH-cU5j
"""

import pandas as pd
import os
import json

# Load the CSV file into a DataFrame
# df = pd.read_csv('')
script_dir = os.path.dirname(os.path.abspath(__file__))

# Construct the path to transaction.csv
csv_file_path = os.path.join(script_dir, 'transaction.csv')
df = pd.read_csv(csv_file_path)

# Preprocess the "Debit money" column by replacing blank rows with 0
df['Debit'] = df['Debit'].fillna(0)

# Convert the "Debit money" column to numeric values
df['Debit'] = pd.to_numeric(df['Debit'], errors='coerce')

# Set your specific money value
threshold_value = 500  # Replace this with your desired value

# Calculate the total amount for each category
category_totals = df.groupby('Category')['Debit'].sum().reset_index()
# print(category_totals)

# Filter categories that cross the specified money value
selected_categories = category_totals[category_totals['Debit'] > threshold_value]

# Convert the result to a JSON object
json_output = selected_categories.to_json(orient='records')

print(json_output)